### PR TITLE
Added new metadata file

### PR DESCRIPTION
**Pull request by thartshorne**
Added the newest metadata file and added unit tests for the new columns

### CODE REVIEW

**Comment by msalganik** [comment]
@vineetbansal can you handle and then accept or reject this new pull request?

**Comment by msalganik** [comment]
@thartshorne are you new tests hooked up to travis-ci so that they can be run every time?

**Comment by thartshorne** [comment]
@msalganik Yes they should be, I built them within the same test file that we had hooked up to Travis-CI before.

**Comment by msalganik** [comment]
Great. Thanks @thartshorne

**Comment by vineetbansal** [comment]
@thartshorne - the metadata_api repo is not being used anymore. metadata_app is the repo for the api as well as web app code. I've moved all open issues from metadata_api to metadata_app.

Can you resubmit the pull request in the metadata_app repo instead? Thanks,

**Pull request closed without merging**
